"use strict";

const fs = require("fs");
const path = require("path");

const GENERATED_MARKER = "<!-- @generated by sync-rules - DO NOT EDIT -->";

function parseFrontmatter(content) {
    const match = content.match(/^---\r?\n([\s\S]+?)\r?\n---\r?\n?([\s\S]*)$/);
    if (!match) return { metadata: {}, body: content.trim() };

    const metadata = {};
    match[1].split(/\r?\n/).forEach((line) => {
        const idx = line.indexOf(":");
        if (idx === -1) return;
        const key = line.slice(0, idx).trim();
        let value = line.slice(idx + 1).trim();
        if (
            (value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'"))
        ) {
            value = value.slice(1, -1);
        }
        if (value === "true") value = true;
        else if (value === "false") value = false;
        metadata[key] = value;
    });

    return { metadata, body: match[2].trim() };
}

function loadRules(rulesDir) {
    if (!fs.existsSync(rulesDir)) {
        console.error(`[Error] Rules directory not found: ${rulesDir}`);
        console.error("  Ensure 'rules/' exists relative to the script location.");
        process.exit(1);
    }

    const files = fs
        .readdirSync(rulesDir)
        .filter((f) => f.endsWith(".md"))
        .sort();

    if (files.length === 0) {
        console.error(`[Error] No .md files found in: ${rulesDir}`);
        process.exit(1);
    }

    return files.map((file) => {
        const raw = fs.readFileSync(path.join(rulesDir, file), "utf8");
        const { metadata, body } = parseFrontmatter(raw);
        const baseName = path.basename(file, ".md");

        return {
            fileName: file,
            name: metadata.name || baseName,
            description: metadata.description || baseName,
            globs: metadata.globs || "",
            alwaysApply: metadata.alwaysApply === true,
            metadata,
            body,
        };
    });
}

function mergeRuleBodies(rules) {
    return rules.map((r) => r.body).join("\n\n---\n\n");
}

function writeMergedFile(filePath, rules) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    const content = `${GENERATED_MARKER}\n\n${mergeRuleBodies(rules)}\n`;
    fs.writeFileSync(filePath, content);
}

module.exports = {
    GENERATED_MARKER,
    parseFrontmatter,
    loadRules,
    mergeRuleBodies,
    writeMergedFile,
};
